### ISSUE TITLE
What about add Right and Left color ?

### ISSUE THREAD

**Issue by X901** [matvdg/Gradient-View#1]
Hi , 
your project is great 
but it will be more helpful
If I can use right color and left color instead of top and bottom 
so Gradation become from right to left

**Comment by calebmanley** [comment]
You can change this using the Start Point and End Point variables.
For left to right you can use the below settings.

Start X = 0
Start Y = 1
End X = 0
End Y = 1

**Comment by matvdg** [comment]
yep, as @calebmanley said, you can do whatever you wants with these variables, but I admit the variables names sound pretty confusing, I'll fix it.

**Comment by dfmarulanda** [comment]
what about center top to center bottom?
