### ISSUE TITLE
Makes UIButton Name Invisible

### ISSUE THREAD

**Issue by HiWaven** [matvdg/Gradient-View#3]
Makes UIButton Name Invisible

I added this class and now I can't see text of my button. Its just invisible.

Swift 4 Xcode Version 9.2 (9C40b)

![screen shot 2018-06-23 at 2 16 04 pm](https://user-images.githubusercontent.com/25354711/41809072-00813ce6-76f0-11e8-91d6-b07ff623a9e5.png)

**Comment by shreyaslad** [comment]
This is for making UIViews into a gradient. You can either set the z index of your text to be above that of the button, or you can composite a similar label on top of the button and constraint it to the button.
I hope this helped :)

**Comment by HiWaven** [comment]
Yes, thank you.
Actually, placing label on top of the button was the first thing I did! 😄
